/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'chaat' : null } |
  { 'soup' : null } |
  { 'sandwich' : null } |
  { 'fastFood' : null } |
  { 'friesSnacks' : null } |
  { 'tandoori' : null };
export interface MenuItem {
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : Category,
  'price' : bigint,
}
export interface RestaurantInfo {
  'hours' : string,
  'instagram' : string,
  'name' : string,
  'whatsapp' : string,
  'email' : string,
  'facebook' : string,
  'address' : string,
  'phone' : string,
}
export interface Review {
  'customerName' : string,
  'date' : string,
  'comment' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'getMenu' : ActorMethod<[], Array<MenuItem>>,
  'getMenuByCategory' : ActorMethod<[Category], Array<MenuItem>>,
  'getRestaurantInfo' : ActorMethod<[], RestaurantInfo>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'submitReview' : ActorMethod<[string, bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];